name: Backend CI/CD
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to GHCR
        run: |
          docker build -t ghcr.io/cryptsendorg/cryptsend-backend:latest .  # 🔥 lowercase
          docker push ghcr.io/cryptsendorg/cryptsend-backend:latest         # 🔥 lowercase

      - name: Deploy to LWS
        if: github.ref == 'refs/heads/develop'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LWS_HOST }}
          username: ${{ secrets.LWS_USER }}
          key: ${{ secrets.LWS_SSH_KEY }}
          script: |
            cd ~/infra || git clone https://github.com/CryptSendOrg/infra.git ~/infra
            cd ~/infra
            git pull origin develop
            docker compose down                                    # 🔥 compose sans tiret
            docker compose pull                                    # 🔥 compose sans tiret
            docker compose up -d --build                           # 🔥 compose sans tiret
            sleep 10
            curl -f http://localhost:3000/health || exit 1
            echo "Deployment successful!"
